{"name": "test_dive", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2.0 == 1", "trace": "def test_dive():\n        result = divide(4, 2)\n>       assert result == 1\nE       assert 2.0 == 1\n\ntest_my_function.py:11: AssertionError"}, "start": 1715785647497, "stop": 1715785647498, "uuid": "dca5c160-19df-471d-b7b0-02d5869f2736", "historyId": "9eeaddf0dd00559fa41dc151887d4d55", "testCaseId": "9eeaddf0dd00559fa41dc151887d4d55", "fullName": "test.test_my_function#test_dive", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_my_function"}, {"name": "host", "value": "H"}, {"name": "thread", "value": "14268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_my_function"}]}